'use strict';
const E=StatementEngine,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let companyHome=true;
let state=E.fresh(false),tab='template',section='income',saveError=false;
// Storage hydrates asynchronously now; loading happens in boot() at the end of this file.
const periods=()=>state.company.comparative?['current','prior']:['current'];
const periodLabel=p=>(p==='current'?state.company.end:state.company.priorEnd)||p;
const money=n=>{const a=Math.abs(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});return n<0?'('+a+')':n===0?'—':a;};
const date=s=>/^\d{4}-\d{2}-\d{2}$/.test(s)?s.split('-').reverse().join('/'):s;
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),4500);}
function save(){try{CompanyStore.write(state);saveError=false;$('#saved').textContent='Saved locally';hoistChanged();}catch(e){saveError=true;$('#saved').textContent='Not saved — download backup';}}
function title(k,h,p,action=''){return `<div class="page-title"><div><span class="eyebrow">${k}</span><h1>${h}</h1><p>${p}</p></div>${action}</div>`;}
function field(label,key,type='text'){return `<label>${label}<input type="${type==='date'?'text':type}" ${type==='date'?'data-date-format="dmy" placeholder="DD/MM/YYYY" maxlength="10"':''} data-company="${key}" value="${esc(type==='date'?date(state.company[key]):state.company[key])}"></label>`;}
function legacyChecks(){const out=[];for(const p of periods()){const c=E.calc(state,p),label=periodLabel(p);out.push({ok:Math.abs(c.balance)<.005,title:`Financial position · ${label}`,detail:`Assets less liabilities and equity: ${money(c.balance)}.`});out.push({ok:Math.abs(c.cashDifference)<.005,title:`Cash flow reconciliation · ${label}`,detail:`Closing cash less financial position cash: ${money(c.cashDifference)}.`});out.push({ok:c.equityDifferences.every(x=>Math.abs(x.value)<.005),title:`Equity reconciliation · ${label}`,detail:c.equityDifferences.filter(x=>Math.abs(x.value)>=.005).map(x=>`${E.groups[x.key]}: ${money(x.value)}`).join('; ')||'All four equity components reconcile.'});}
if(state.company.comparative){let current=state.equity.current,prev=E.calc(state,'prior');out.push({ok:Math.abs(state.cash.current.opening-prev.sum('cash'))<.005,title:'Opening cash continuity',detail:'Current opening cash must match comparative closing cash.'});out.push({ok:['Capital','Reserve','Retained','Owner'].every(k=>Math.abs(current['open'+k]-prev.sum(k.toLowerCase()))<.005),title:'Opening equity continuity',detail:'Current opening equity components must match comparative closing balances.'});}
out.push({ok:!!state.company.name.trim(),title:'Company name',detail:'Enter the registered company name.'});let c=state.company;const validDate=d=>/^\d{4}-\d{2}-\d{2}$/.test(d)&&!Number.isNaN(Date.parse(d))&&new Date(d).toISOString().slice(0,10)===d;out.push({ok:validDate(c.start)&&validDate(c.end)&&c.start<=c.end&&(!c.comparative||(validDate(c.priorStart)&&validDate(c.priorEnd)&&c.priorStart<=c.priorEnd&&c.priorEnd<c.start)),title:'Reporting periods',detail:'Use valid dates; the comparative period must end before the current period begins.'});out.push({ok:state.rows.every(r=>r.label.trim()&&(!r.note||state.notes.some(n=>n.id===r.note))),title:'Line descriptions and note references',detail:'Every line needs a description and any linked note must exist.'});out.push({ok:state.notes.length>0&&state.notes.every(n=>n.title.trim()&&(n.autoGroup?(ComparisonNotes.detail(state,n).reviewed&&(!ComparisonNotes.detail(state,n).needsExplanation||n.body.trim())):n.body.trim())),title:'Notes completed',detail:'Complete manual disclosures and review automatic notes against the latest figures. Add explanations for flagged movements.'});out.push({ok:!!state.management.trim(),title:'Management report',detail:'Add the management report in Company details.'});return out;}
function checks(){return HM.checks(state);}
function reportHtml(){return hoistReportHtml();}
function reportView(){return hoistReportView();}
function render(){if(companyHome){renderCompanyHome();return;}$('#company-home').hidden=true;$('.app').hidden=false;renderCompanySwitcher();HoistDisclosureDrafts.populate(state);const pages=[['company','01','Company details'],['figures','02','Financial figures'],['import','↑','Trial balance import'],['mapping','03','Note mapping'],['template','04','Entity & authorisation'],['policies','05','Accounting policies'],['support','06','Supporting schedules'],['cashdetail','07','Cash-flow details'],['tax','08','Corporate tax'],['disclosures','09','Disclosures'],['readiness','10','Report readiness'],['report','11','Report preview']];$('#nav').innerHTML=pages.map(([k,n,l])=>`<button data-tab="${k}" class="${tab===k?'active':''}"><span>${n}</span>${l}</button>`).join('');$('#companybar').textContent=state.company.name||'Untitled company';$('#saved').textContent=saveError?'Not saved — download backup':'Saved locally';const pending=HM.checks(state).filter(x=>!x.ok).length;$('#view').innerHTML=`<div class="demo"><span><b id="preparation-identity">${esc(preparationIdentity())}</b> · <span id="hoist-ready-count">${esc(readinessSummary(HM.checks(state)))}</span></span><button data-tab="readiness">View preparation status →</button></div>`+(state.demo?'<div class="demo"><b>Illustrative data only</b><button data-action="new">Start blank report</button></div>':'')+({company:companyView,figures:figuresView,import:tbImportView,mapping:mappingView,template:templateView,policies:policyView,support:supportView,cashdetail:cashDetailView,tax:taxView,disclosures:disclosureView,readiness:readinessView,checks:readinessView,notes:notesView,report:reportView}[tab])();}
function companyView(){return title('01 / SETUP','Company details','Set the entity, reporting dates and presentation for your report pack.')+`<section class="card"><h2>Reporting entity</h2><div class="form-grid">${field('Registered company name','name')}${field('Registration / licence number','registration')}${field('Registered address','address')}${field('Principal activity','activity')}${field('Manager / authorised signatory','manager')}<label>Presentation currency<select data-company="currency">${['AED','USD','EUR','GBP','SAR','INR'].map(v=>`<option ${state.company.currency===v?'selected':''}>${v}</option>`).join('')}</select></label></div></section><section class="card"><h2>Reporting period</h2><div class="form-grid">${field('Period start','start','date')}${field('Period end','end','date')}</div><label class="checklabel"><input type="checkbox" data-company="comparative" ${state.company.comparative?'checked':''}> Include comparative figures</label>${state.company.comparative?`<div class="form-grid">${field('Comparative period start','priorStart','date')}${field('Comparative period end','priorEnd','date')}</div>`:''}</section><section class="card"><h2>Management report</h2><p class="muted">Describe the activities, performance and developments for the period. Names entered here do not constitute signatures.</p><textarea data-management rows="7" aria-label="Management report" placeholder="Write the management report…">${esc(state.management)}</textarea></section><section class="card"><h2>Report presentation</h2><label>Layout<select data-company="style"><option value="classic" ${state.company.style==='classic'?'selected':''}>Classic — restrained serif typography</option><option value="ruled" ${state.company.style==='ruled'?'selected':''}>Contemporary — ruled headings</option></select></label><p class="muted">Inspired by the structure and comparative tables in your five samples. Auditor opinions, signatures and stamps are not generated.</p><div class="actions"><button data-action="new">New blank report</button><button data-action="demo">Load illustrative example</button></div></section>`;}
const sections={income:'Profit or loss',position:'Financial position',equity:'Equity movements',cash:'Cash flows'};
const sectionGroups={income:['revenue','cost','otherIncome','expense','finance','tax','oci'],position:['noncurrentAsset','currentAsset','cash','noncurrentLiability','currentLiability','capital','reserve','retained','owner']};
function figuresView(){const c=E.calc(state,'current');return title('02 / PREPARE','Financial figures','Enter closing balances and period totals. Your statements update automatically.',`<div class="actions"><button data-tab="import" class="primary">↑ Import trial balance</button><button data-tab="report">View report ↗</button></div>`)+`<div class="metrics"><div><span>Revenue · ${esc(state.company.currency)}</span><strong>${money(c.sum('revenue'))}</strong></div><div><span>Profit / (loss)</span><strong>${money(c.profit)}</strong></div><div><span>Total assets</span><strong>${money(c.assets)}</strong></div><div class="${Math.abs(c.balance)<.005?'good':'warning'}"><span>Balance difference</span><strong>${money(c.balance)}</strong><small>${Math.abs(c.balance)<.005?'Financial position balances':'Review assets, liabilities and equity'}</small></div></div><div class="tabs">${Object.entries(sections).map(([k,v])=>`<button data-section="${k}" class="${section===k?'selected':''}">${v}</button>`).join('')}</div>${sectionGroups[section]?rowsEditor():scheduleEditor()}`;}
function numberInput(value,attrs,label){return `<input class="amount" type="number" step="0.01" min="-1000000000000" max="1000000000000" value="${value}" ${attrs} aria-label="${esc(label)}">`;}
function headers(first='Description',notes=false){return `<thead><tr><th>${first}</th>${notes?'<th>Note</th>':''}${periods().map(p=>`<th class="numeric">${esc(periodLabel(p))}<small>${esc(state.company.currency)}</small></th>`).join('')}<th></th></tr></thead>`;}
function rowsEditor(){return `<div class="hint">${section==='income'?'Enter revenue and expenses as positive amounts. Expenses are deducted automatically. Use negative amounts for reversals.':'Enter net carrying values. Liabilities and capital are positive; accumulated losses and debit shareholders’ balances are negative.'}</div><section class="card table-card"><div class="table-scroll"><table class="editor">${headers('Account / line item',true)}<tbody>${sectionGroups[section].map(g=>`<tr class="group"><th colspan="${periods().length+3}">${E.groups[g]}</th></tr>${state.rows.filter(r=>r.group===g).map(r=>`<tr><td><input data-row="${esc(r.id)}" data-prop="label" value="${esc(r.label)}" aria-label="Line description"></td><td><select data-row="${esc(r.id)}" data-prop="note" aria-label="Linked note"><option value="">—</option>${state.notes.map((n,i)=>`<option value="${esc(n.id)}" ${r.note===n.id?'selected':''}>${i+1}. ${esc(n.title)}</option>`).join('')}</select></td>${periods().map(p=>`<td>${numberInput(r[p],`data-row="${esc(r.id)}" data-prop="${p}"`,r.label+' '+p)}</td>`).join('')}<td><button class="icon" data-delete-row="${esc(r.id)}" aria-label="Delete ${esc(r.label)}">×</button></td></tr>`).join('')}<tr class="addrow"><td colspan="${periods().length+3}"><button data-add="${g}">＋ Add line</button></td></tr>`).join('')}</tbody></table></div></section>`;}
function scheduleEditor(){const cash=section==='cash',kind=cash?'cash':'equity',fields=cash?E.cashFields:E.eqFields;return `<div class="hint">${cash?'Indirect method: profit is linked automatically. Enter cash inflows as positive and outflows as negative. Enter actual movements; the app does not infer cash flows from closing balances.':'Opening balances and movements are entered separately for each period. Profit is linked automatically. Other comprehensive income is allocated to reserves; disclose its composition in the notes.'}</div><section class="card table-card"><div class="table-scroll"><table class="editor">${headers('Schedule input')}<tbody>${Object.entries(fields).map(([k,l])=>`<tr><td>${l}</td>${periods().map(p=>`<td>${numberInput(state[kind][p][k],`data-schedule="${kind}" data-period="${p}" data-key="${k}"`,l+' '+p)}</td>`).join('')}<td></td></tr>`).join('')}</tbody></table></div></section><section class="card"><h2>${cash?'Cash flow reconciliation':'Calculated closing equity'}</h2>${financialTable(cash?[['Profit / (loss)',p=>E.calc(state,p).profit],['Net operating cash flows',p=>E.calc(state,p).operating],['Closing cash and cash equivalents',p=>E.calc(state,p).closingCash],['Difference to financial position',p=>E.calc(state,p).cashDifference]]:Object.entries({capital:'Share capital',reserve:'Reserves',retained:'Retained earnings',owner:'Shareholders’ current account'}).map(([k,l])=>[l,p=>E.calc(state,p).close[k]]))}</section>`;}
function notesView(){return title('03 / DISCLOSE','Notes & policies','Write company-specific disclosures and link them to statement lines.',`<button data-action="add-note">＋ Add note</button>`)+comparisonControls()+`<div class="hint">Use these headings as a starting point. Assess applicable accounting policies, tax, going concern and other disclosures with your accountant. The app does not determine compliance or calculate tax.</div>`+state.notes.map((n,i)=>`<section class="card note"><div class="note-heading"><span class="note-number">${String(i+1).padStart(2,'0')}</span><input aria-label="Note ${i+1} title" data-note="${esc(n.id)}" data-prop="title" value="${esc(n.title)}"><button class="icon" data-delete-note="${esc(n.id)}" aria-label="Delete note ${i+1}">×</button></div>${n.autoGroup?comparisonContent(n,true)+'<label>Explanation / additional disclosure</label>':''}<textarea rows="6" data-note="${esc(n.id)}" data-prop="body" placeholder="Enter disclosure…" aria-label="Note ${i+1} text">${esc(n.body)}</textarea></section>`).join('');}
function checksView(){let list=checks(),n=list.filter(c=>!c.ok).length;return title('04 / REVIEW','Review checks',n?`${n} items need attention before the report is ready for review.`:'Arithmetic and completion checks passed. Review the accounting treatment separately.')+`<div class="checks">${list.map(c=>`<section class="check ${c.ok?'pass':'fail'}"><span>${c.ok?'✓':'!'}</span><div><h3>${c.title}</h3><p>${esc(c.detail)}</p></div><b>${c.ok?'Passed':'Review'}</b></section>`).join('')}</div><p class="muted">These checks test arithmetic, period continuity and completion. They are not an audit or a financial reporting compliance assessment.</p>`;}
function financialTable(rows,notes=false){return `<div class="table-scroll"><table class="financial">${headers('Particulars',notes)}<tbody>${rows.map(r=>r.heading?`<tr class="report-group"><th colspan="${periods().length+(notes?3:2)}">${esc(r.heading)}</th></tr>`:`<tr class="${r[2]?'total':''}"><td>${esc(r[0])}</td>${notes?`<td>${esc(r[3]||'')}</td>`:''}${periods().map(p=>`<td class="numeric">${money(r[1](p))}</td>`).join('')}<td></td></tr>`).join('')}</tbody></table></div>`;}
function noteNo(id){const i=state.notes.findIndex(n=>n.id===id);return i<0?'':String(i+1);}
function reportRows(groups){return groups.flatMap(g=>state.rows.filter(r=>r.group===g).map(r=>[r.label,p=>r[p],false,noteNo(r.note)]));}
function legacyReportHtml(){let c=state.company,seq=0;const period=`For the period ${date(c.start)} to ${date(c.end)}`,names=['Company information and management report','Statement of financial position','Statement of profit or loss and other comprehensive income','Statement of changes in equity','Statement of cash flows','Notes to the financial statements'];const sheet=(heading,body)=>`<article class="paper ${esc(c.style)}"><div class="paper-head"><strong>${esc(c.name||'Company name not entered')}</strong><span>DRAFT · UNAUDITED</span></div><h2>${esc(heading)}</h2><p class="period">${esc(period)}</p>${body}<div class="paper-foot"><span>The accompanying notes form part of these draft financial statements.</span><span>${++seq}</span></div></article>`;
const income=[...reportRows(['revenue','cost']),['Gross profit / (loss)',p=>E.calc(state,p).gross,true],...reportRows(['otherIncome','expense','finance','tax']),['Profit / (loss) for the period',p=>E.calc(state,p).profit,true],...reportRows(['oci']),['Total comprehensive income / (loss)',p=>E.calc(state,p).comprehensive,true]];
const position=[{heading:'ASSETS'},{heading:'Non-current assets'},...reportRows(['noncurrentAsset']),['Total non-current assets',p=>E.calc(state,p).sum('noncurrentAsset'),true],{heading:'Current assets'},...reportRows(['currentAsset','cash']),['Total current assets',p=>E.add([E.calc(state,p).sum('currentAsset'),E.calc(state,p).sum('cash')]),true],['TOTAL ASSETS',p=>E.calc(state,p).assets,true],{heading:'EQUITY AND LIABILITIES'},{heading:'Equity'},...reportRows(['capital','reserve','retained','owner']),['Total equity',p=>E.calc(state,p).equity,true],{heading:'Non-current liabilities'},...reportRows(['noncurrentLiability']),['Total non-current liabilities',p=>E.calc(state,p).sum('noncurrentLiability'),true],{heading:'Current liabilities'},...reportRows(['currentLiability']),['Total current liabilities',p=>E.calc(state,p).sum('currentLiability'),true],['TOTAL EQUITY AND LIABILITIES',p=>E.add([E.calc(state,p).liabilities,E.calc(state,p).equity]),true]];
const cf=[{heading:'Cash flows from operating activities'},['Profit / (loss) for the period',p=>E.calc(state,p).profit],...['noncash','working','operatingOther'].map(k=>[E.cashFields[k],p=>state.cash[p][k]]),['Net cash from / (used in) operating activities',p=>E.calc(state,p).operating,true],{heading:'Cash flows from investing activities'},['Net cash from / (used in) investing activities',p=>state.cash[p].investing,true],{heading:'Cash flows from financing activities'},['Net cash from / (used in) financing activities',p=>state.cash[p].financing,true],['Exchange effect on cash',p=>state.cash[p].fx],['Net change including exchange effect',p=>E.calc(state,p).change,true],['Opening cash and cash equivalents',p=>state.cash[p].opening],['Closing cash and cash equivalents',p=>E.calc(state,p).closingCash,true]];
const eq=periods().slice().reverse().map(p=>{const e=state.equity[p],cc=E.calc(state,p),rows=[['Opening balance',e.openCapital,e.openReserve,e.openRetained,e.openOwner],['Profit / (loss)',0,0,cc.profit,0],['Other comprehensive income',0,cc.sum('oci'),0,0],['Capital introduced / (repaid)',e.capitalMovement,0,0,0],['Transfers to reserves',0,e.reserveTransfer,-e.reserveTransfer,0],['Dividends',0,0,-e.dividends,0],['Shareholders’ account movement',0,0,0,e.ownerMovement],['Other retained earnings adjustments',0,0,e.otherRetained,0],['Closing balance',cc.close.capital,cc.close.reserve,cc.close.retained,cc.close.owner]];return `<h3>Period ended ${esc(date(periodLabel(p)))}</h3><div class="table-scroll"><table class="financial equity-table"><thead><tr>${['Movement','Share capital','Reserves','Retained earnings','Shareholders’ account','Total'].map(v=>`<th>${v}</th>`).join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr class="${i===8?'total':''}"><td>${r[0]}</td>${r.slice(1).map(v=>`<td class="numeric">${money(v)}</td>`).join('')}<td class="numeric">${money(E.add(r.slice(1)))}</td></tr>`).join('')}</tbody></table></div>`;}).join('');
const warnings=checks().filter(x=>!x.ok);return `<article class="paper cover ${esc(c.style)}"><div class="paper-head"><span>FINANCIAL STATEMENTS</span><span>DRAFT · UNAUDITED</span></div><div class="cover-title"><div class="cover-rule"></div><h1>${esc(c.name||'Company name not entered')}</h1><h2>Financial statements</h2><p>${esc(period)}</p><p>Presented in ${esc(c.currency)}</p>${c.comparative?`<p class="muted">Comparative period: ${esc(date(c.priorStart))} to ${esc(date(c.priorEnd))}</p>`:''}</div><p class="cover-status">Prepared for review${state.demo?' · ILLUSTRATIVE DATA':''}</p><p>This pack is prepared from user-entered information. It contains no independent auditor’s opinion.</p>${warnings.length?`<div class="report-warning">${warnings.length} preparation checks require attention. See the review summary below.</div>`:''}</article>`+sheet('Contents',`<ol class="contents">${names.map((n,i)=>`<li><span>${n}</span><b>${i+2}</b></li>`).join('')}</ol><p class="muted">Numbers refer to report sections. Long disclosures may continue onto additional printed pages.</p>${warnings.length?`<h3>Preparation review summary</h3><ul>${warnings.map(w=>`<li>${esc(w.title)} — ${esc(w.detail)}</li>`).join('')}</ul>`:''}`)+sheet(names[0],`<dl>${[['Registered name',c.name],['Registration / licence',c.registration],['Registered address',c.address],['Principal activity',c.activity],['Manager / authorised signatory',c.manager]].map(([k,v])=>`<dt>${k}</dt><dd>${esc(v||'Not entered')}</dd>`).join('')}</dl><h3>Management report</h3><div class="prose">${esc(state.management||'Management report not entered.')}</div>`)+sheet(names[1],financialTable(position,true))+sheet(names[2],`<p class="muted">Expense lines are shown as positive amounts and deducted in the totals.</p>${financialTable(income,true)}`)+sheet(names[3],`<p>All amounts in ${esc(c.currency)}. Other comprehensive income is allocated to reserves.</p>${eq}`)+sheet(names[4],`<p>Indirect method. Outflows are shown in parentheses.</p>${financialTable(cf)}`)+sheet(names[5],state.notes.map((n,i)=>`<section class="disclosure"><h3>${i+1}. ${esc(n.title||'Untitled note')}</h3>${n.autoGroup?comparisonContent(n):''}<div class="prose">${esc(n.body||(n.autoGroup?'':'Disclosure not entered.'))}</div>${!n.autoGroup&&state.rows.some(r=>r.note===n.id)?financialTable(state.rows.filter(r=>r.note===n.id).map(r=>[r.label,p=>r[p]])):''}</section>`).join(''));}
function legacyReportView(){return title('05 / OUTPUT','Report preview','A comparative statement pack, ready to print on A4.',`<button data-action="print" class="primary">Print / Save PDF ↗</button>`)+`<div class="hint">Choose “Save as PDF” in the print dialog. Use A4, 100% scale and turn off browser headers and footers.</div><div class="report-stack">${reportHtml()}</div>`;}
function download(){const a=document.createElement('a');const u=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.href=u;a.download=(state.company.name||'statement').replace(/[^a-z0-9 -]/gi,'').trim()+'-'+state.company.end+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);toast('Backup downloaded. Keep this file to restore your draft.');}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.tab){tab=b.dataset.tab;render();window.scrollTo(0,0);return;}if(b.dataset.section){section=b.dataset.section;render();return;}if(b.dataset.add){state.rows.push({id:crypto.randomUUID(),label:'New line',group:b.dataset.add,current:0,prior:0,note:''});save();render();return;}if(b.dataset.deleteRow){if(!confirm('Delete this financial line?'))return;state.rows=state.rows.filter(r=>r.id!==b.dataset.deleteRow);save();render();return;}if(b.dataset.deleteNote){if(!confirm('Delete this note and remove its line references?'))return;state.notes=state.notes.filter(n=>n.id!==b.dataset.deleteNote);state.rows.forEach(r=>{if(r.note===b.dataset.deleteNote)r.note=''});save();render();return;}switch(b.dataset.action){case 'backup':download();break;case 'restore':$('#restore').click();break;case 'new':case 'demo':if(!confirm('Replace the current draft? Download a backup first if you want to keep it.'))return;state=b.dataset.action==='demo'?createSampleReport():E.fresh(false);tab='company';save();render();break;case 'add-note':state.notes.push({id:crypto.randomUUID(),title:'New disclosure',body:''});save();render();break;case 'print':hoistGeneratePdf(true);break;}});
document.addEventListener('change',e=>{const t=e.target;if(t.id==='restore')return;let changed=false;if(t.dataset.dateFormat){if(!saveDateField(t))return;changed=true;}else if(t.dataset.company){state.company[t.dataset.company]=t.type==='checkbox'?t.checked:t.value;changed=true;}if(t.hasAttribute('data-management')){state.management=t.value;changed=true;}if(t.dataset.note){const n=state.notes.find(n=>n.id===t.dataset.note);n[t.dataset.prop]=t.value;changed=true;}if(t.dataset.row){const r=state.rows.find(r=>r.id===t.dataset.row),k=t.dataset.prop;if(['current','prior'].includes(k)){if(!t.validity.valid||!Number.isFinite(Number(t.value))){toast('Enter a valid amount with at most two decimal places.');render();return;}r[k]=Number(t.value);}else r[k]=t.value;changed=true;}if(t.dataset.schedule){if(!t.validity.valid||!Number.isFinite(Number(t.value))){toast('Enter a valid amount with at most two decimal places.');render();return;}state[t.dataset.schedule][t.dataset.period][t.dataset.key]=Number(t.value);changed=true;}if(changed){save();if(t.dataset.company==='comparative'){render();}else{ $('#companybar').textContent=state.company.name||'Untitled company'; if(tab==='figures'){const temp=document.createElement('div');temp.innerHTML=figuresView(); const metric=$('.metrics');if(metric)metric.innerHTML=temp.querySelector('.metrics').innerHTML; const schedules=$('#view > section.card:not(.table-card)'); const next=temp.querySelector('section.card:not(.table-card)');if(schedules&&next)schedules.innerHTML=next.innerHTML;}}}});
// Save text while typing without replacing the focused editor.
document.addEventListener('input',e=>{const t=e.target;if(t.dataset.dateFormat){saveDateField(t);return;}if(t.hasAttribute('data-management')){state.management=t.value;save();}else if(t.dataset.note){state.notes.find(n=>n.id===t.dataset.note)[t.dataset.prop]=t.value;save();}else if(t.dataset.company&&t.type!=='checkbox'){state.company[t.dataset.company]=t.value;save();}else if(t.dataset.row&&['label','note'].includes(t.dataset.prop)){state.rows.find(r=>r.id===t.dataset.row)[t.dataset.prop]=t.value;save();}});
$('#restore').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>3000000)throw Error('Backup must be under 3 MB.');const next=E.validate(JSON.parse(await file.text()));if(confirm('Replace the current draft with this backup?')){state=next;save();render();toast('Draft restored.');}}catch(err){toast('Could not restore: '+err.message);}finally{e.target.value='';}});
window.addEventListener('beforeprint',()=>{$('#print-report').innerHTML=reportHtml();});

function renderCompanySwitcher(){const el=$('#company-switcher');if(el)el.innerHTML='<button data-home-action="back" class="back-companies">← All companies</button>';}
function renderCompanyHome(){const entries=CompanyStore.list();$('.app').hidden=true;const home=$('#company-home');home.hidden=false;home.innerHTML=`<div class="company-top"><a class="home-brand" href="#">Statement Studio</a><span>Financial statement preparation</span></div><div class="company-content"><div class="company-heading"><div><span class="eyebrow">YOUR WORKSPACE</span><h1>Companies</h1><p>Select a company to continue preparing its financial statements.</p></div><button class="primary" data-home-action="new">+ New company</button></div><form id="company-create" hidden><h2>Create company</h2><label>Registered company name<input id="new-company-name" required maxlength="250" placeholder="Enter company name" autocomplete="organization"></label><div><button type="submit" class="primary">Create & open workspace</button><button type="button" data-home-action="cancel">Cancel</button></div><p id="company-create-error" role="alert"></p></form><div class="company-list-head"><h2>Your companies <span>${entries.length}</span></h2><span>Each company has a separate preparation workspace</span></div><div class="company-grid">${entries.map(c=>`<article class="company-card"><div class="company-monogram" aria-hidden="true">${esc((c.name||'C').slice(0,1).toUpperCase())}</div><h2>${esc(c.name)}</h2><p>Reporting period ending <strong>${esc(date(c.end)||'Not set')}</strong></p><div class="company-card-bottom"><span>Saved locally</span><button data-open-company="${esc(c.id)}" aria-label="Open ${esc(c.name)}">Open preparation →</button></div></article>`).join('')}</div><p class="company-home-note">Company files are stored in this browser. Download backups from each preparation workspace to keep a separate copy.</p></div>`;}
function resetCompanySession(){tbSession={sheets:[],sheet:0,header:0,columns:{},mode:'split',decimal:'dot',period:'current',closeProfit:true,overrides:{},preview:null,reviewed:false,error:'',loading:false,name:''};companyHome=false;tab='company';hoistChanged();render();}
document.addEventListener('change',e=>{if(e.target.id!=='company-choice')return;try{if(!CompanyStore.blocked)CompanyStore.write(state);state=CompanyStore.select(e.target.value);saveError=false;resetCompanySession();}catch(err){toast(err.message);renderCompanySwitcher();}});
document.addEventListener('click',e=>{if(e.target.id!=='add-company')return;const name=prompt('Name of the new company / audit file:');if(!name?.trim())return;try{if(!CompanyStore.blocked)CompanyStore.write(state);state=CompanyStore.create(name.trim());saveError=false;resetCompanySession();toast('New company created. Your other company files are saved.');}catch(err){toast(err.message);}});
window.addEventListener('storage',e=>{CompanyStore.external(e.key);if(CompanyStore.blocked){saveError=true;$('#saved').textContent='Changed in another tab - reload before editing';}else if(e.key==='hoistx-companies-v1')renderCompanySwitcher();});

document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.openCompany){state=CompanyStore.select(b.dataset.openCompany);saveError=false;resetCompanySession();window.scrollTo(0,0);}if(b.dataset.homeAction==='back'){if(!CompanyStore.blocked)CompanyStore.write(state);companyHome=true;render();window.scrollTo(0,0);}if(b.dataset.homeAction==='new'){$('#company-create').hidden=false;$('#new-company-name').focus();}if(b.dataset.homeAction==='cancel')$('#company-create').hidden=true;}catch(err){toast(err.message);}});
document.addEventListener('submit',e=>{if(e.target.id!=='company-create')return;e.preventDefault();const name=$('#new-company-name').value.trim();if(!name)return;try{state=CompanyStore.create(name);saveError=false;resetCompanySession();window.scrollTo(0,0);}catch(err){$('#company-create-error').textContent=err.message;}});

// Nothing may touch storage until StoreBackend has hydrated from disk / localStorage.
// Event listeners above are registered immediately; none can fire before the first render.
async function boot(){
 try{await StoreBackend.ready;}
 catch(err){
  // Never present a blank page: an unreadable store must say so, and must not
  // be written over by a fresh empty state.
  const home=$('#company-home');home.hidden=false;
  home.innerHTML=`<div class="company-content"><div class="company-heading"><div><span class="eyebrow">STORAGE</span><h1>Could not load your companies</h1><p>${esc(err.message)}</p></div></div><p class="company-home-note">Your saved data has not been changed. Close and reopen the application. If this persists, restore a backup from the Backups folder.</p></div>`;
  return;
 }
 try{const old=CompanyStore.init();if(old)state=E.validate(JSON.parse(old));}catch(err){saveError=true;}
 render();hoistChanged();
}
// A failed disk write is reported late, so surface it rather than losing it silently.
window.addEventListener('statementstudio:save-failed',e=>{saveError=true;const el=$('#saved');if(el)el.textContent='Not saved — download backup';});
boot();
