(function(root){
'use strict';const M=root.HoistModel,E=root.StatementEngine;
const fields={referenceRate:'Reference tax rate for reconciliation (%)',taxableIncome:'Taxable income per reviewed computation',permanentEffect:'Tax effect of permanent differences',reliefEffect:'Tax effect of reliefs / different rates (negative for reduction)',otherEffect:'Other tax reconciliation effects',currentExpense:'Current-period current tax expense / (credit)',priorAdjustment:'Adjustments for prior-period current tax',deferredExpense:'Deferred tax expense / (credit)',openingPayable:'Opening current tax payable / (receivable)',paid:'Current tax paid (positive)',otherPayable:'Other current-tax payable movements',closingPayable:'Closing current tax payable / (receivable)',openingDeferredAsset:'Opening deferred tax asset',deferredAssetPnl:'Deferred tax asset movement in profit or loss',deferredAssetOther:'Other deferred tax asset movements',closingDeferredAsset:'Closing deferred tax asset',openingDeferredLiability:'Opening deferred tax liability',deferredLiabilityPnl:'Deferred tax liability movement in profit or loss',deferredLiabilityOther:'Other deferred tax liability movements',closingDeferredLiability:'Closing deferred tax liability'};
const fresh=()=>({registration:'',regime:'',basis:'',current:Object.fromEntries(Object.keys(fields).map(k=>[k,0])),prior:Object.fromEntries(Object.keys(fields).map(k=>[k,0]))});
const ensureOld=M.ensure;M.ensure=s=>{const t=ensureOld(s);if(!t.tax)t.tax=fresh();return t;};
M.defs[17]=['Corporate income tax',['tax','currentAsset','noncurrentAsset','currentLiability','noncurrentLiability']];
const balance=(s,p,groups)=>E.add(M.rows(s,17).filter(r=>groups.includes(r.group)).map(r=>r[p]));
function calc(s,p){const x=M.ensure(s).tax[p],expense=E.calc(s,p).sum('tax'),pbt=E.add([E.calc(s,p).profit,expense]),reference=Math.round(pbt*x.referenceRate)/100;return {pbt,expense,reference,totalExpense:E.add([x.currentExpense,x.priorAdjustment,x.deferredExpense]),bridge:E.add([reference,x.permanentEffect,x.reliefEffect,x.otherEffect]),payable:E.add([x.openingPayable,x.currentExpense,x.priorAdjustment,-x.paid,x.otherPayable]),targetPayable:E.add([balance(s,p,['currentLiability']),-balance(s,p,['currentAsset'])]),deferredAsset:E.add([x.openingDeferredAsset,x.deferredAssetPnl,x.deferredAssetOther]),deferredLiability:E.add([x.openingDeferredLiability,x.deferredLiabilityPnl,x.deferredLiabilityOther])};}
const oldChecks=M.checks;M.checks=s=>{const t=M.ensure(s),out=oldChecks(s),eq=(a,b)=>Math.abs(E.add([a,-b]))<.005,add=(ok,title,detail)=>out.push({ok:!!ok,title,detail,tab:'tax'});for(const [k,l] of [['registration','Tax registration position'],['regime','Corporate tax regime'],['basis','Tax computation and deferred-tax basis']])add(t.tax[k].trim(),l,'Enter the actual reviewed position, including why no registration or tax is due if applicable.');
for(const p of M.periods(s)){const x=t.tax[p],c=calc(s,p),label=p==='current'?s.company.end:s.company.priorEnd;add(x.referenceRate>=0&&x.referenceRate<=100,'Reference tax rate '+label,'Enter a percentage between 0 and 100.');add(eq(c.totalExpense,c.expense),'Current / deferred tax expense '+label,'Current expense + prior adjustments + deferred expense must equal income tax in the statements.');add(eq(c.bridge,c.expense),'Effective tax reconciliation '+label,'Tax at reference rate plus listed effects must equal total tax expense.');add(eq(c.payable,x.closingPayable)&&eq(x.closingPayable,c.targetPayable),'Current tax payable '+label,'The tax payable roll-forward must equal the mapped note 17 current tax balances.');add(eq(c.deferredAsset,x.closingDeferredAsset)&&eq(x.closingDeferredAsset,balance(s,p,['noncurrentAsset'])),'Deferred tax asset '+label,'Roll-forward must equal mapped note 17 non-current tax assets.');add(eq(c.deferredLiability,x.closingDeferredLiability)&&eq(x.closingDeferredLiability,balance(s,p,['noncurrentLiability'])),'Deferred tax liability '+label,'Roll-forward must equal mapped note 17 non-current tax liabilities.');add(eq(E.add([x.deferredLiabilityPnl,-x.deferredAssetPnl]),x.deferredExpense),'Deferred tax through profit or loss '+label,'Liability movement less asset movement must equal the deferred tax expense.');add(x.paid>=0&&x.closingDeferredAsset>=0&&x.closingDeferredLiability>=0,'Tax payment and deferred balances '+label,'Enter payments and deferred asset/liability balances as positive amounts.');}
if(s.company.comparative)for(const [a,b] of [['openingPayable','closingPayable'],['openingDeferredAsset','closingDeferredAsset'],['openingDeferredLiability','closingDeferredLiability']])add(eq(t.tax.current[a],t.tax.prior[b]),'Tax opening balance continuity: '+a,'Current opening balance must equal the comparative closing balance.');return out;};
const oldValidate=M.validate;M.validate=s=>{oldValidate(s);if(s.hoist?.tax){const t=s.hoist.tax;for(const k of ['registration','regime','basis'])if(typeof t[k]!=='string'||t[k].length>60000)throw Error('Invalid tax disclosure.');for(const p of ['current','prior'])for(const k of Object.keys(fields))if(typeof t[p]?.[k]!=='number'||!Number.isFinite(t[p][k])||Math.abs(t[p][k])>1e12)throw Error('Invalid tax schedule.');}return s;};
root.HoistTax={fields,fresh,calc,balance};if(typeof module!=='undefined')module.exports=root.HoistTax;
})(globalThis);
