'use strict';
let tbSession={sheets:[],sheet:0,header:0,columns:{},mode:'split',decimal:'dot',period:'current',closeProfit:true,overrides:{},preview:null,reviewed:false,error:'',loading:false,name:''};
function tbGrid(){return tbSession.sheets[tbSession.sheet]?.grid||[];}
function tbDetect(){const grid=tbGrid();let best=0,score=-1;for(let i=0;i<Math.min(grid.length,30);i++){const c=TrialBalance.autoColumns(grid[i]);const n=(c.name>=0?3:0)+(c.debit>=0?2:0)+(c.credit>=0?2:0)+(c.balance>=0?2:0);if(n>score){best=i;score=n;}}
 tbSession.header=best;tbSession.columns=TrialBalance.autoColumns(grid[best]||[]);tbSession.mode=tbSession.columns.debit>=0&&tbSession.columns.credit>=0?'split':'debitPositive';tbSession.preview=null;tbSession.overrides={};tbSession.error='';}
function tbColumn(label,key){const row=tbGrid()[tbSession.header]||[];return `<label>${label}<select data-tb-column="${key}"><option value="-1">${['code','group'].includes(key)?'Not included':'Choose column'}</option>${row.map((v,i)=>`<option value="${i}" ${tbSession.columns[key]===i?'selected':''}>${i+1} · ${esc(String(v||'Unnamed column').slice(0,80))}</option>`).join('')}</select></label>`;}
function tbImportView(){const t=tbSession,source=t.sheets[t.sheet],p=t.preview;
return title('02 / IMPORT','Trial balance import','Import one period at a time. Review the mapping before updating your financial figures.',`<a class="button-link" href="trial-balance-template.csv" download>↓ Download CSV template</a>`)+
`<section class="card"><h2>1. Choose your trial balance</h2><p class="muted">Excel (.xlsx / .xls), CSV or tab-separated text · Up to 5 MB · Up to 495 accounts. Files are read in your browser.</p><p class="muted">Use adjusted closing balances, not period movement totals. Remove report titles and subtotals or exclude them in the preview.</p><div class="tb-upload"><label>Choose file<input type="file" id="tb-file" accept=".xlsx,.xls,.csv,.tsv,.txt" ${t.loading?'disabled':''}></label><span>${esc(t.loading?'Reading workbook…':t.name||'No file selected')}</span></div><details><summary>Or paste rows copied from Excel</summary><textarea id="tb-paste" rows="5" aria-label="Paste trial balance" placeholder="Account Code    Account Name    Debit    Credit"></textarea><button data-tb-action="paste">Read pasted rows</button></details>${t.error?`<div class="tb-error" role="alert">${esc(t.error)}</div>`:''}</section>`+
(t.sheets.length?`<section class="card"><h2>2. Match your columns</h2><div class="form-grid"><label>Worksheet<select id="tb-sheet">${t.sheets.map((s,i)=>`<option value="${i}" ${i===t.sheet?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label><label>Import into<select id="tb-period"><option value="current" ${t.period==='current'?'selected':''}>Current period · ${esc(state.company.end)}</option><option value="prior" ${t.period==='prior'?'selected':''}>Comparative period · ${esc(state.company.priorEnd)}</option></select></label></div>${source?.error?`<div class="tb-error">${esc(source.error)}</div>`:`<div class="form-grid"><label>Header row<input type="number" id="tb-header" min="1" max="${tbGrid().length}" value="${t.header+1}"></label><label>Amount format<select id="tb-mode"><option value="split" ${t.mode==='split'?'selected':''}>Separate debit and credit columns</option><option value="debitPositive" ${t.mode==='debitPositive'?'selected':''}>One balance column · positive = debit</option><option value="creditPositive" ${t.mode==='creditPositive'?'selected':''}>One balance column · positive = credit</option></select></label><label>Number format<select id="tb-decimal"><option value="dot" ${t.decimal==='dot'?'selected':''}>1,234.56 · decimal point</option><option value="comma" ${t.decimal==='comma'?'selected':''}>1.234,56 · decimal comma</option></select></label>${tbColumn('Account code (optional)','code')}${tbColumn('Account name','name')}${t.mode==='split'?tbColumn('Debit','debit')+tbColumn('Credit','credit'):tbColumn('Signed balance','balance')}${tbColumn('Statement category (optional)','group')}</div>${source?.formulas?`<div class="hint">This worksheet has ${source.formulas} formula cells. Saved results are used; formulas are not recalculated. Recalculate and save in Excel before importing.</div>`:''}<label class="checklabel"><input type="checkbox" id="tb-close" ${t.closeProfit?'checked':''}> Add this period’s profit to retained earnings and OCI to reserves</label><p class="muted">Keep this selected for a trial balance before the profit-and-loss accounts are closed. Disable it only when those amounts are already included in closing equity. Tax and closing adjustments must already be recorded in your trial balance.</p><button data-tb-action="preview" class="primary">Review accounts →</button>`}</section>`:'')+
(p?`<section class="card"><h2>3. Review accounts and checks</h2><div class="metrics tb-metrics"><div><span>Included accounts</span><strong>${p.count}</strong></div><div><span>Total debits</span><strong>${money(p.debit)}</strong></div><div><span>Total credits</span><strong>${money(p.credit)}</strong></div><div class="${p.difference===0?'good':'warning'}"><span>Difference</span><strong>${money(p.difference)}</strong></div></div><div class="hint">Suggested categories need your review. Total rows are excluded by default and remain visible below. Accumulated depreciation belongs with its asset category so it reduces the asset balance. Loans, deposits and related-party balances may need manual classification.</div>${p.errors.length||p.unmapped.length||!p.count||p.count>495?`<div class="tb-error">${p.errors.length} invalid rows · ${p.unmapped.length} unmapped accounts.${p.count>495?' Maximum 495 accounts.':''}${!p.count?' Include at least one account.':''} Correct the source or mapping before applying.</div>`:''}<div class="table-scroll"><table class="tb-table"><thead><tr><th>Include</th><th>Account</th><th class="numeric">Debit</th><th class="numeric">Credit</th><th>Statement category</th></tr></thead><tbody>${p.rows.map(r=>`<tr class="${r.included?'':'tb-excluded'}"><td><input type="checkbox" data-tb-include="${r.source}" ${r.included?'checked':''} aria-label="Include row ${r.source+1}"><small>Row ${r.source+1}</small></td><td><b>${esc(r.name||'(missing name)')}</b><small>${esc(r.code)}${r.total?' · Total row':''}</small>${r.error?`<span class="tb-row-error">${esc(r.error)}</span>`:''}</td><td class="numeric">${money(r.debit)}</td><td class="numeric">${money(r.credit)}</td><td><select data-tb-group="${r.source}" aria-label="Category for ${esc(r.name)}"><option value="">Choose category</option>${Object.entries(E.groups).map(([k,l])=>`<option value="${k}" ${r.group===k?'selected':''}>${esc(l)}</option>`).join('')}</select></td></tr>`).join('')}</tbody></table></div><div id="tb-impact">${tbImpact()}</div><label class="checklabel"><input type="checkbox" id="tb-reviewed" ${t.reviewed?'checked':''}> I have reviewed included rows, categories and the equity closing option.</label><div class="actions"><button data-tb-action="apply" class="primary" ${!p.valid||!t.reviewed?'disabled':''}>Apply to ${t.period==='current'?'current':'comparative'} period</button><button data-action="backup">Download current draft backup</button></div></section>`:'')+
`<section class="card"><h2>Import behaviour</h2><p class="muted">Import replaces all financial figures for the selected period. Accounts are matched by code (or exact name when no code is available). Figures for the other period, linked notes and existing cash-flow/equity schedules are retained. Review schedules after importing. Importing into the illustrative example clears all example figures and schedules first.</p><button data-tb-action="undo">Undo last trial balance import</button><p class="muted">Undo restores the complete draft saved immediately before the last import, including any figures you have edited since then.</p></section>`;
}
function tbImpact(){if(!tbSession.preview?.valid)return '<div class="hint">An exactly balanced trial balance and a category for every included account are required.</div>';try{const next=TrialBalance.apply(state,tbSession.preview,tbSession.period,tbSession.closeProfit),c=E.calc(next,tbSession.period);return `<div class="hint"><b>Statement preview · ${esc(tbSession.period==='current'?state.company.end:state.company.priorEnd)}</b><br>Profit / (loss): ${money(c.profit)} · Total assets: ${money(c.assets)} · Balance difference: ${money(c.balance)}${c.balance!==0?'<br>The resulting statement does not balance. Review the equity closing option and account categories.':''}${state.demo?'<br>All illustrative figures and schedules will be cleared.':''}</div>`;}catch(err){return `<div class="tb-error">${esc(err.message)}</div>`;}}
function tbPreview(){try{const opts={header:tbSession.header,columns:tbSession.columns,mode:tbSession.mode,decimal:tbSession.decimal};let p=TrialBalance.prepare(tbGrid(),opts,tbSession.overrides);
 for(const r of p.rows){if(tbSession.overrides[r.source]?.group!==undefined)continue;const match=state.rows.find(x=>x.tbKey===r.key);if(match)tbSession.overrides[r.source]={...tbSession.overrides[r.source],group:match.group};}
 tbSession.preview=TrialBalance.prepare(tbGrid(),opts,tbSession.overrides);tbSession.error='';tbSession.reviewed=false;
 }catch(err){tbSession.preview=null;tbSession.error=err.message;}render();}
function readTBWorkbook(buffer){return new Promise((resolve,reject)=>{const embedded=document.getElementById('embedded-tb-worker');const workerUrl=embedded?URL.createObjectURL(new Blob([JSON.parse(embedded.textContent)],{type:'text/javascript'})):'tb-worker.js';const w=new Worker(workerUrl);const timeout=setTimeout(()=>{w.terminate();reject(Error('Reading took too long. Export the trial balance sheet as CSV.'));},20000);const done=()=>{clearTimeout(timeout);w.terminate();if(embedded)URL.revokeObjectURL(workerUrl);};w.onmessage=e=>{done();e.data.error?reject(Error(e.data.error)):resolve(e.data.sheets);};w.onerror=()=>{done();reject(Error('Could not load the Excel reader. Try CSV or reload this page.'));};w.postMessage(buffer,[buffer]);});}
document.addEventListener('change',async e=>{
 const t=e.target;
 if(t.id==='tb-file'){const file=t.files?.[0];if(!file)return;tbSession.preview=null;tbSession.error='';tbSession.loading=true;render();try{if(file.size>5*1024*1024)throw Error('File must be no larger than 5 MB.');const ext=file.name.split('.').pop().toLowerCase();if(['csv','tsv','txt'].includes(ext)){const bytes=await file.arrayBuffer();let text;if(new Uint8Array(bytes)[0]===255&&new Uint8Array(bytes)[1]===254)text=new TextDecoder('utf-16le').decode(bytes);else text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);tbSession.sheets=[{name:'Imported rows',grid:TrialBalance.parseDelimited(text,ext==='tsv'?'\t':undefined)}];}else if(['xlsx','xls'].includes(ext))tbSession.sheets=await readTBWorkbook(await file.arrayBuffer());else throw Error('Choose Excel (.xlsx / .xls), CSV or TSV.');tbSession.sheet=0;tbSession.name=file.name;tbDetect();}catch(err){tbSession.sheets=[];tbSession.error=err.message;}finally{tbSession.loading=false;render();}return;}
 if(t.id==='tb-sheet'){tbSession.sheet=Number(t.value);tbDetect();render();return;}
 if(t.id==='tb-header'){const n=Number(t.value)-1;if(!Number.isInteger(n)||n<0||n>=tbGrid().length){tbSession.error='Choose a valid header row.';render();return;}tbSession.header=n;tbSession.columns=TrialBalance.autoColumns(tbGrid()[n]);tbSession.overrides={};tbSession.preview=null;render();return;}
 if(t.dataset.tbColumn){tbSession.columns[t.dataset.tbColumn]=Number(t.value);tbSession.preview=null;tbSession.reviewed=false;render();return;}
 const settings={'tb-period':'period','tb-mode':'mode','tb-decimal':'decimal','tb-close':'closeProfit'};
 if(settings[t.id]){tbSession[settings[t.id]]=t.type==='checkbox'?t.checked:t.value;tbSession.preview=null;tbSession.reviewed=false;render();return;}
 if(t.dataset.tbInclude!==undefined||t.dataset.tbGroup!==undefined){const row=Number(t.dataset.tbInclude??t.dataset.tbGroup);tbSession.overrides[row]={...tbSession.overrides[row],...(t.dataset.tbGroup!==undefined?{group:t.value}:{included:t.checked})};tbPreview();return;}
 if(t.id==='tb-reviewed'){tbSession.reviewed=t.checked;const b=document.querySelector('[data-tb-action="apply"]');if(b)b.disabled=!t.checked||!tbSession.preview?.valid;}
});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-tb-action]');if(!b)return;switch(b.dataset.tbAction){
 case 'paste':try{tbSession.sheets=[{name:'Pasted rows',grid:TrialBalance.parseDelimited($('#tb-paste').value)}];tbSession.sheet=0;tbSession.name='Pasted rows';tbDetect();}catch(err){tbSession.error=err.message;}render();break;
 case 'preview':tbPreview();break;
 case 'apply':try{if(!tbSession.reviewed)throw Error('Confirm you have reviewed the mapping.');const next=TrialBalance.apply(state,tbSession.preview,tbSession.period,tbSession.closeProfit);if(!confirm(`Replace all ${tbSession.period==='current'?'current':'comparative'}-period figures with ${tbSession.preview.count} imported accounts? ${state.demo?'All illustrative figures and schedules will be cleared. ':''}A restore point will be saved for Undo.`))return;await StoreBackend.writeUndo(CompanyStore.active,JSON.stringify(state));CompanyStore.write(next);state=next;saveError=false;hoistChanged();tbSession.preview=null;tab='figures';section='position';render();toast('Trial balance imported. Review your cash-flow and equity schedules.');}catch(err){tbSession.error=err.message;render();}break;
 case 'undo':try{const raw=await StoreBackend.readUndo(CompanyStore.active);if(!raw)throw Error('No previous import restore point is available for this company.');const before=E.validate(JSON.parse(raw));if(!confirm('Restore the complete draft from before the last trial balance import? This also replaces edits made since that import.'))return;CompanyStore.write(before);state=before;hoistChanged();await StoreBackend.clearUndo(CompanyStore.active);tbSession.preview=null;saveError=false;render();toast('Draft restored to before the last import.');}catch(err){tbSession.error=err.message;render();}break;
}});
